# Wordpress application with MariaDB using Docker Compose

services:
  db:
    image: mariadb:11.4
    container_name: wp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: wp
    volumes:
      - ./dbdata:/var/lib/mysql

  app:
    image: wordpress:6-php8.2-apache
    container_name: wp-app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8083:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
    volumes:
      - ./site:/var/www/html
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini