services:
  db:
    image: mariadb:11.4
    container_name: joomla-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla
      MYSQL_ROOT_PASSWORD: joomla
    volumes:
      - ./dbdata:/var/lib/mysql

  app:
    image: joomla:5.4-php8.2-apache
    container_name: joomla-app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      JOOMLA_DB_HOST: db:3306
      JOOMLA_DB_NAME: joomla
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomla
    volumes:
      - ./site:/var/www/html
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
